/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "SharedMemServer.h"
#include <stdio.h>

bool_t
xdr_sharedmem(xdrs, objp)
    register XDR *xdrs;
    sharedmem *objp;
{

    register long *buf;

    if (!xdr_array(xdrs, (char **)&objp->sharedmem_val, (u_int *) &objp->sharedmem_len, ~0,
        sizeof (char), (xdrproc_t) xdr_char))
        return (FALSE);
    return (TRUE);
}

bool_t
xdr_createsharedmem(xdrs, objp)
    register XDR *xdrs;
    createsharedmem *objp;
{

    register long *buf;

    if (!xdr_int(xdrs, &objp->ikey))
        return (FALSE);
    if (!xdr_int(xdrs, &objp->isize))
        return (FALSE);
    return (TRUE);
}

bool_t
xdr_writesharedmem(xdrs, objp)
    register XDR *xdrs;
    writesharedmem *objp;
{

    register long *buf;

    if (!xdr_int(xdrs, &objp->ikey))
        return (FALSE);
    if (!xdr_sharedmem(xdrs, &objp->data))
        return (FALSE);
    return (TRUE);
}

bool_t
xdr_sharedmemretval(xdrs, objp)
    register XDR *xdrs;
    sharedmemretval *objp;
{

    register long *buf;

    if (!xdr_int(xdrs, &objp->iretval))
        return (FALSE);
    if (!xdr_string(xdrs, &objp->serrormsg, ~0))
        return (FALSE);
    return (TRUE);
}
