/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SHAREDMEMSERVER_H_RPCGEN
#define    _SHAREDMEMSERVER_H_RPCGEN

#include <rpc/rpc.h>

typedef struct {
    u_int sharedmem_len;
    char *sharedmem_val;
} sharedmem;

struct createsharedmem {
    int ikey;
    int isize;
};
typedef struct createsharedmem createsharedmem;

struct writesharedmem {
    int ikey;
    sharedmem data;
};
typedef struct writesharedmem writesharedmem;

struct sharedmemretval {
    int iretval;
    char *serrormsg;
};
typedef struct sharedmemretval sharedmemretval;

#define    crossplatformmem ((unsigned long)(0x22200000))
#define    crossplatformmemver ((unsigned long)(1))
#define    createmem ((unsigned long)(1))
extern  sharedmemretval * createmem_1(createsharedmem *, CLIENT *);
#define    write ((unsigned long)(2))
extern  sharedmemretval * write_1(writesharedmem *, CLIENT *);
#define    read ((unsigned long)(3))
extern  sharedmem * read_1(createsharedmem *, CLIENT *);
#define    removemem ((unsigned long)(4))
extern  sharedmemretval * removemem_1(int *, CLIENT *);
extern int crossplatformmem_1_freeresult();

/* the xdr functions */
extern bool_t xdr_sharedmem(XDR *, sharedmem *);
extern bool_t xdr_createsharedmem(XDR *, createsharedmem *);
extern bool_t xdr_writesharedmem(XDR *, writesharedmem *);
extern bool_t xdr_sharedmemretval(XDR *, sharedmemretval *);

#endif /* !_SHAREDMEMSERVER_H_RPCGEN */
