/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "SharedMemServer.h"
#include <stdio.h>
#include <stdlib.h> /* getenv, exit */

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

sharedmemretval *
createmem_1(argp, clnt)
    createsharedmem *argp;
    CLIENT *clnt;
{
    static sharedmemretval clnt_res;

    memset((char *)&clnt_res, 0, sizeof (clnt_res));
    if (clnt_call(clnt, createmem,
        (xdrproc_t) xdr_createsharedmem, (caddr_t) argp,
        (xdrproc_t) xdr_sharedmemretval, (caddr_t) &clnt_res,
        TIMEOUT) != RPC_SUCCESS) {
        return (NULL);
    }
    return (&clnt_res);
}

sharedmemretval *
write_1(argp, clnt)
    writesharedmem *argp;
    CLIENT *clnt;
{
    static sharedmemretval clnt_res;

    memset((char *)&clnt_res, 0, sizeof (clnt_res));
    if (clnt_call(clnt, write,
        (xdrproc_t) xdr_writesharedmem, (caddr_t) argp,
        (xdrproc_t) xdr_sharedmemretval, (caddr_t) &clnt_res,
        TIMEOUT) != RPC_SUCCESS) {
        return (NULL);
    }
    return (&clnt_res);
}

sharedmem *
read_1(argp, clnt)
    createsharedmem *argp;
    CLIENT *clnt;
{
    static sharedmem clnt_res;

    memset((char *)&clnt_res, 0, sizeof (clnt_res));
    if (clnt_call(clnt, read,
        (xdrproc_t) xdr_createsharedmem, (caddr_t) argp,
        (xdrproc_t) xdr_sharedmem, (caddr_t) &clnt_res,
        TIMEOUT) != RPC_SUCCESS) {
        return (NULL);
    }
    return (&clnt_res);
}

sharedmemretval *
removemem_1(argp, clnt)
    int *argp;
    CLIENT *clnt;
{
    static sharedmemretval clnt_res;

    memset((char *)&clnt_res, 0, sizeof (clnt_res));
    if (clnt_call(clnt, removemem,
        (xdrproc_t) xdr_int, (caddr_t) argp,
        (xdrproc_t) xdr_sharedmemretval, (caddr_t) &clnt_res,
        TIMEOUT) != RPC_SUCCESS) {
        return (NULL);
    }
    return (&clnt_res);
}
