/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOAN_SYSTEM2_H_RPCGEN
#define	_LOAN_SYSTEM2_H_RPCGEN

#include <rpc/rpc.h>
#define	MAX_BANK_NAME 512
#define	MAX_PAYMENTS 360

struct ssinglepayment {
	int iPeriod;
	double dPayment;
	double dInterest;
	double dPrincipal;
	double dAmountRemaining;
};
typedef struct ssinglepayment ssinglepayment;

struct spaymentinfo {
	struct {
		u_int sBankName_len;
		char *sBankName_val;
	} sBankName;
	double dPayment;
};
typedef struct spaymentinfo spaymentinfo;

struct sschedual {
	ssinglepayment listofpayments[MAX_PAYMENTS];
};
typedef struct sschedual sschedual;

#define	payments ((unsigned long)(0x22000000))
#define	paymentsver ((unsigned long)(1))
#define	dGetPayment ((unsigned long)(1))
extern  spaymentinfo * dgetpayment_1(double *);
#define	sGetListOfPayments ((unsigned long)(2))
extern  sschedual * sgetlistofpayments_1(double *);
extern int payments_1_freeresult();

/* the xdr functions */
extern bool_t xdr_ssinglepayment(XDR *, ssinglepayment *);
extern bool_t xdr_spaymentinfo(XDR *, spaymentinfo *);
extern bool_t xdr_sschedual(XDR *, sschedual *);

#endif /* !_LOAN_SYSTEM2_H_RPCGEN */
