/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "loan_system2.h"

bool_t
xdr_ssinglepayment(xdrs, objp)
    register XDR *xdrs;
    ssinglepayment *objp;
{

    register long *buf;

    if (!xdr_int(xdrs, &objp->iPeriod))
        return (FALSE);
    if (!xdr_double(xdrs, &objp->dPayment))
        return (FALSE);
    if (!xdr_double(xdrs, &objp->dInterest))
        return (FALSE);
    if (!xdr_double(xdrs, &objp->dPrincipal))
        return (FALSE);
    if (!xdr_double(xdrs, &objp->dAmountRemaining))
        return (FALSE);
    return (TRUE);
}

bool_t
xdr_spaymentinfo(xdrs, objp)
    register XDR *xdrs;
    spaymentinfo *objp;
{

    register long *buf;

    if (!xdr_array(xdrs, (char **)&objp->sBankName.sBankName_val, (u_int *) &objp->sBankName.sBankName_len, MAX_BANK_NAME,
        sizeof (char), (xdrproc_t) xdr_char))
        return (FALSE);
    if (!xdr_double(xdrs, &objp->dPayment))
        return (FALSE);
    return (TRUE);
}

bool_t
xdr_sschedual(xdrs, objp)
    register XDR *xdrs;
    sschedual *objp;
{

    register long *buf;

    int i;
    if (!xdr_vector(xdrs, (char *)objp->listofpayments, MAX_PAYMENTS,
        sizeof (ssinglepayment), (xdrproc_t) xdr_ssinglepayment))
        return (FALSE);
    return (TRUE);
}
