/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CROSSPLATFORMSEM_H_RPCGEN
#define    _CROSSPLATFORMSEM_H_RPCGEN

#include <rpc/rpc.h>

typedef char *semname;

struct semstruct {
    semname ssemname;
    int iinitvalue;
    int imaxvalue;
};
typedef struct semstruct semstruct;

struct retvalstruct {
    int iretval;
    char *serrormsg;
};
typedef struct retvalstruct retvalstruct;

#define    crossplatformsem ((unsigned long)(0x22100000))
#define    crossplatformsemver ((unsigned long)(1))
#define    createsem ((unsigned long)(1))
extern  retvalstruct * createsem_1(semstruct *, CLIENT *);
#define    closesem ((unsigned long)(2))
extern  retvalstruct * closesem_1(semname *, CLIENT *);
#define    removesem ((unsigned long)(3))
extern  retvalstruct * removesem_1(semname *, CLIENT *);
#define    lockwait ((unsigned long)(4))
extern  retvalstruct * lockwait_1(semname *, CLIENT *);
#define    locknowait ((unsigned long)(5))
extern  retvalstruct * locknowait_1(semname *, CLIENT *);
#define    unlock ((unsigned long)(6))
extern  retvalstruct * unlock_1(semname *, CLIENT *);
#define    getvalue ((unsigned long)(7))
extern  retvalstruct * getvalue_1(semname *, CLIENT *);
extern int crossplatformsem_1_freeresult();

/* the xdr functions */
extern bool_t xdr_semname(XDR *, semname *);
extern bool_t xdr_semstruct(XDR *, semstruct *);
extern bool_t xdr_retvalstruct(XDR *, retvalstruct *);

#endif /* !_CROSSPLATFORMSEM_H_RPCGEN */
