/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "CrossPlatformSem.h"

bool_t
xdr_semname(xdrs, objp)
	register XDR *xdrs;
	semname *objp;
{

	register long *buf;

	if (!xdr_string(xdrs, objp, ~0))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_semstruct(xdrs, objp)
	register XDR *xdrs;
	semstruct *objp;
{

	register long *buf;

	if (!xdr_semname(xdrs, &objp->ssemname))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->iaccessmode))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->iinitvalue))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->imaxvalue))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_retvalstruct(xdrs, objp)
	register XDR *xdrs;
	retvalstruct *objp;
{

	register long *buf;

	if (!xdr_int(xdrs, &objp->iretval))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->serrormsg, ~0))
		return (FALSE);
	return (TRUE);
}
