/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOAN_SYSTEM_H_RPCGEN
#define    _LOAN_SYSTEM_H_RPCGEN

#include <rpc/rpc.h>
#define    MAX_BANK_NAME 512

struct spaymentinfo {
    struct {
        u_int sBankName_len;
        char *sBankName_val;
    } sBankName;
    double dPayment;
};
typedef struct spaymentinfo spaymentinfo;

#define    payments ((unsigned long)(0x21000000))
#define    paymentsver ((unsigned long)(1))
#define    dGetPayment ((unsigned long)(1))
extern  spaymentinfo * dgetpayment_1(double *);
extern int payments_1_freeresult();

/* the xdr functions */
extern bool_t xdr_spaymentinfo(XDR *, spaymentinfo *);

#endif /* !_LOAN_SYSTEM_H_RPCGEN */
