/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "loan_system.h"

bool_t
xdr_spaymentinfo(xdrs, objp)
	register XDR *xdrs;
	spaymentinfo *objp;
{

	register long *buf;

	if (!xdr_array(xdrs, (char **)&objp->sBankName.sBankName_val, (u_int *) &objp->sBankName.sBankName_len, MAX_BANK_NAME,
		sizeof (char), (xdrproc_t) xdr_char))
		return (FALSE);
	if (!xdr_double(xdrs, &objp->dPayment))
		return (FALSE);
	return (TRUE);
}
