/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CROSSPLATFORMSEM_H_RPCGEN
#define    _CROSSPLATFORMSEM_H_RPCGEN

#include <rpc/rpc.h>
#include "retval.h"

#define    OPEN_SEM 0
#define    CREATE_OR_OPEN_1
#define CREATE_SEM 2

typedef char *semname;

struct semstruct {
    semname ssemname;
    int iaccessmode;
    int iinitvalue;
};
typedef struct semstruct semstruct;

/*
struct retvalstruct {
    int iretval;
    char *serrormsg;
};
typedef struct retvalstruct retvalstruct;
*/

#define    crossplatformsem ((unsigned long)(0x22100000))
#define    crossplatformsemver ((unsigned long)(1))
#define    icreatesem ((unsigned long)(1))
extern  retvalstruct * icreatesem_1(semstruct *, CLIENT *);
#define    iclosesem ((unsigned long)(2))
extern  retvalstruct * iclosesem_1(semname *, CLIENT *);
#define    iremovesemaphore ((unsigned long)(3))
extern  retvalstruct * iremovesemaphore_1(semname *, CLIENT *);
#define    ilockwait ((unsigned long)(4))
extern  retvalstruct * ilockwait_1(semname *, CLIENT *);
#define    ilocknowait ((unsigned long)(5))
extern  retvalstruct * ilocknowait_1(semname *, CLIENT *);
#define    iunlock ((unsigned long)(6))
extern  retvalstruct * iunlock_1(semname *, CLIENT *);
extern int crossplatformsem_1_freeresult();

/* the xdr functions */
extern bool_t xdr_semname();
extern bool_t xdr_semstruct();
/*extern bool_t xdr_retvalstruct(XDR *, char *);*/

#endif /* !_CROSSPLATFORMSEM_H_RPCGEN */
